name: CI

on:
  push:
    
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libreoffice make texlive-xetex texlive-fonts-extra

      - name: Build pdfs
        run: |
          make
          make clean
      
      - name: Commit pdf files
        if: ${{ github.ref_name == 'main' }}
        working-directory: pdfs
        run: | 
          git config user.email "bot@turtlesec.no"
          git config user.name "Turtle Bot (GitHub Action)"
          if [[ "$( git status --porcelain)" != "" ]]; then
            git add *.pdf
            git commit -m "Updated pdf files"
            git push
          fi

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        if: ${{ github.ref_name != 'main' }} && ${{ always() }}
        with:
          retention-days: 3  
          name: pdfs
          path: pdfs/
