name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install make texlive-xetex texlive-fonts-extra

      - name: Build pdfs
        run: |
          make
          make clean
      
      - name: Commit pdf files
        working-directory: pdfs
        run: | 
          git config user.email "bot@turtlesec.no"
          git config user.name "Turtle Bot (GitHub Action)"
          if [[ "$( git status --porcelain)" != "" ]]; then
            git add *.pdf
            git commit -m "Updated pdf files"
            git push
          fi
